### ISSUE TITLE
Can't start `rookout` synchronously

### ISSUE THREAD

**Issue by javinor** [Rookout/docs#244]
I'm opening the issue here, since the repo for `rookout` npm module is private.

The behavior for [`rookout.startSync`](https://github.com/Rookout/docs/blob/50cc1b83943740a0baf38ab6b619ac84e266f172/docs/sdk-setup.md#startsync) is problematic. To use it I need `deasync` installed, but it doesn't appear in the `package.json` deps - I'm working in an environment that doesn't allow `require`ing deps that aren't declared.

Could you add `deasync` to the project deps? Or maybe return a promise from `rookout.start` that will resolve only after initialization is over? I'm guessing there's a reason you're using `deasync`, but I just want to make sure you considered this...

**Comment by LiranLast** [comment]
Hi, @javinor thanks for reaching out to us!

Most Rookout customers prefer using `rookout.start` which returns a promise (we might need to clarify the docs).

We do not include the `deasync` package by default as it includes a native extension and can complicate deployments under certain conditions.

We would love to continue the conversation here, in-app chat, mail or any way you feel comfortable.

**Comment by javinor** [comment]
I missed the part about `rookout.start` returning a promise. Thanks!
