### ISSUE TITLE
broken link regarding DOP

### ISSUE THREAD

**Issue by carehart** [Rookout/docs#497]
The setup guide page has [a section on Data On-Prem](https://docs.rookout.com/docs/setup-guide/#rookout-data-on-prem-optional) which has a broken link in its "visit this page" which goes to https://docs.rookout.com/docs/setup-guide/dop-intro.md, but that gets a 404, and I couldn't find any page at all that was like this (which is why I am not offering this as a PR).

I suppose I could offer a PR that simply removed it, but instead I'll offer it here as an issue for your consideration, about whether to remove the link or correct it.

**Comment by LiranLast** [comment]
@lirook can you take a look?

**Comment by lirook** [comment]
Hey @carehart, thank you for pointing this issue out!
As we have #489 almost ready, I will close this for now, and it should be resolved pretty soon.
Thanks again.

**Comment by lirook** [comment]
Reopening so we can track this issue.

**Comment by carehart** [comment]
Ah, OK. That's indeed a great bunch of content on the topic.

**Comment by lirook** [comment]
This issue was just fixed. Thanks again!
