### ISSUE TITLE
Documentation on Agile Flame Graphs feature

### ISSUE THREAD

**Issue by Venryx** [Rookout/docs#501]
I've been searching for the last half-hour for documentation on the "Agile Flame Graphs" feature, mentioned in various places:

The Rookout live-debugger info page: https://www.rookout.com/solutions/live-debugger
>  Real Time Profiling
> Leverage agile flame graphs to measure the execution time of any function or code snippet without worrying about performance hits

An article on Global News Wire: https://www.globenewswire.com/news-release/2021/03/23/2197886/0/en/Rookout-Launches-Agile-Flame-Graphs-to-Dynamically-Profile-Distributed-Applications-in-Production.html
> “Until today, developers were blind to the performance of this code in production environments, due to the significant performance overhead of profiling tools,” said Liran Haimovitch, CTO and Co-Founder of Rookout. “Agile Flame Graphs allows software engineers to select a section of code and instantly visualize the latency between functions and individual lines of code, within and across distributed systems.” [...]
>
> “Nobody profiles code anymore because traditional tools have too much overhead to use in production and local environments don’t match the reality of scale,” said Patrick Lightbody, Co-founder of Reclaim.ai, Former SVP of Product at New Relic. “Rookout's Agile Flame Graphs give us the ability to instantly collect ad-hoc performance metrics from any line of code which is critical when dealing with live incidents.”

An article on vmblog.com: https://vmblog.com/archive/2021/03/22/vmblog-expert-interview-shahar-fogel-of-rookout-talks-modern-debugging-understandability-and-agile-flame-graphs.aspx
> VMblog:  You have a new product that looks great called Agile Flame Graphs.  Can you tell the readers a little more about it and how it helps developers better understand their applications?
>
> Fogel:  Flame graphs are the type of graph you expect to see when tackling the complex challenge of profiling an application, in an attempt to find performance bottlenecks and identify the areas in your code that cause high latency, or the "hot spots" that get hit so frequently that they just get stuck, and cause a poor user experience and even crashes.
> 
> The purpose of the flame graph is to show you a color-coded breakdown of the time spent in different areas of your code. Traditional tools for profiling applications are too resource intensive to use broadly in production without a significant negative impact on application performance. They also come with a lot of noise, and can only really be operated effectively by operations experts. We wanted to simplify the traditional flame graph to just the most necessary information, so that it could be visualized easily and it didn't create a ton of overhead, while giving engineers the most precise information and metrics related to the performance of their application and code-base.
![image](https://user-images.githubusercontent.com/5303978/149038280-3cee91ac-fa7c-4331-955f-c891df727ee6.png)

Yet I can't find anything in the Rookout documentation showing how to utilize the feature! (I've searched for "flame" in this repo, and the [NodeJS tutorial repo](https://github.com/Rookout/tutorial-nodejs), and got zero results)

I also tried looking for the feature in the NodeJS demo here: https://app.rookout.com/org/Sandbox/debugger

But I couldn't see any way to add profiling points, or to display the Flame Graph interface shown in the screenshot above.

**Comment by lirook** [comment]
Hey @Venryx , thank you for reaching out and pointing out that we are missing documentation regarding Rookout Profiling. We are working on updating our documentation on how to integrate with tracing tools to enable profiling, and we hope to have an update soon.
I should note that the Profiling feature is currently not support in our Node.JS SDK, but it is available in some of the other languages we support. We will take your comment into consideration when we plan and prioritize our profiling support for Node.js. In the meantime, feel free to contact our support team to learn how to use profiling in other languages supported by Rookout.
Thanks again.
